Organization:
- Work
  - 1 test: defining functions for part 1, testing on test input
  - 1 run: getting answer for part 1
  - 2 test: ...
  - 2 run: ...
- Utilities: functions I think might help parse general inputs
- Inputs: where I define the test (_t_) and problem (_s_) inputs

# Work

## 1 test

The tallest rock is 4 units tall, so after 2022 steps the tower can be at most 8088 blocks tall. So a 8100 x 7 chamber would be enough to store all the data.

Start with a floor of rock in the cave, and one by one drop rocks subject to the jets of air.

In [42]:
# Parse the input
jets = clean(t)
n = len(jets)
jets

'>>><<><>><<<>><>>><<<>>><<<><<<>><>><<>>'

In [43]:
# (i,j) of bottom left corner of the square hitbox
def create_rock(i, j, k_rock):
    rock = []
    match k_rock:
        case 0:
            rock = [(i,j), (i,j+1), (i,j+2), (i,j+3)]
        case 1:
            rock = [(i,j+1), (i-1,j), (i-1,j+1), (i-1,j+2), (i-2,j+1)]
        case 2:
            rock = [(i,j), (i,j+1), (i,j+2), (i-1,j+2), (i-2,j+2)]
        case 3:
            rock = [(i,j), (i-1,j), (i-2,j), (i-3,j)]
        case 4:
            rock = [(i,j), (i,j+1), (i-1,j), (i-1,j+1)]
    
    # Sanity check
    assert rock
    
    return rock

# Return the new rock location and a flag for whether we should still be dropping
def update(rock, k_jet):
    ## Jet
    
    # Jet direction
    if jets[k_jet] == '<':
        d = -1
    else:
        d = 1
    
    # Tentative new rock
    new_rock = [(i,j+d) for i,j in rock]
    
    # Check if this was valid
    valid = True
    for i,j in new_rock:
        # Out of bounds
        if not (0 <= j < 7):
            valid = False
            break
        
        # Collide with the cave
        if cave[i,j]:
            valid = False
            break
    
    # Apply the jet only if the sideways push was valid
    if valid:
        rock = new_rock
    
    ## Drop
    
    # Tentative new rock
    new_rock = [(i+1,j) for i,j in rock]
    
    # Check if this was valid
    valid = True
    for i,j in new_rock:
        # Collide with the cave
        if cave[i,j]:
            valid = False
            break
    
    # Apply the drop only if valid
    # If the drop was valid, we can keep moving this rock
    if valid:
        rock = new_rock
        dropping_flag = True
    else:
        dropping_flag = False
    
    return rock, dropping_flag

def print_cave(rows):
    for row in cave[-rows:,:]:
        print(''.join(['#' if b else '.' for b in row]))

In [44]:
import numpy as np

In [66]:
# Empty cave
cave = np.zeros((8100, 7), dtype=bool)

# Rock floor
cave[-1,:] = True

In [67]:
# Number of rocks to drop
num_rocks = 10

# Keep a running counter of which jet we're using next
k_jet = 0

# And an index for the lowest empty row
i_empty = 8098

# Iterate through rocks
for k in range(num_rocks):
    # For peace of mind:
    assert i_empty > 10
    
    # The rock we'll drop
    k_rock = k % 5
    
    # Create the rock as its locations in space
    rock = create_rock(i_empty - 3, 2, k_rock)
    
    # Drop the rock according to the running count of jets
    dropping_flag = True
    while dropping_flag:
        # Try to apply the jets and drop the rock
        rock, dropping_flag = update(rock, k_jet)
        k_jet = (k_jet + 1) % n
    
    # Finalize the position of the rock and update the empty row
    for i,j in rock:
        cave[i,j] = True
        i_empty = min(i_empty, i-1)

In [68]:
print_cave(20)

.......
.......
....#..
....#..
....##.
##..##.
######.
.###...
..#....
.####..
....##.
....##.
....#..
..#.#..
..#.#..
#####..
..###..
...#...
..####.
#######


In [69]:
# Empty cave
cave = np.zeros((8100, 7), dtype=bool)

# Rock floor
cave[-1,:] = True

# Number of rocks to drop
num_rocks = 2022

# Keep a running counter of which jet we're using next
k_jet = 0

# And an index for the lowest empty row
i_empty = 8098

# Iterate through rocks
for k in range(num_rocks):
    # For peace of mind:
    assert i_empty > 10
    
    # The rock we'll drop
    k_rock = k % 5
    
    # Create the rock as its locations in space
    rock = create_rock(i_empty - 3, 2, k_rock)
    
    # Drop the rock according to the running count of jets
    dropping_flag = True
    while dropping_flag:
        # Try to apply the jets and drop the rock
        rock, dropping_flag = update(rock, k_jet)
        k_jet = (k_jet + 1) % n
    
    # Finalize the position of the rock and update the index of the lowest empty row
    for i,j in rock:
        cave[i,j] = True
        i_empty = min(i_empty, i-1)

In [73]:
# len(cave) - i_empty is roughly the height of the tower, except
# Minus 1 because indices start at zero
# Minus 1 because I filled in the floor of the cave
len(cave) - i_empty - 2

3068

## 1 run

In [82]:
# Parse the input
jets = clean(s)
n = len(jets)

In [83]:
# Empty cave
cave = np.zeros((8100, 7), dtype=bool)

# Rock floor
cave[-1,:] = True

# Number of rocks to drop
num_rocks = 2022

# Keep a running counter of which jet we're using next
k_jet = 0

# And an index for the lowest empty row
i_empty = 8098

# Iterate through rocks
for k in range(num_rocks):
    # For peace of mind:
    assert i_empty > 10
    
    # The rock we'll drop
    k_rock = k % 5
    
    # Create the rock as its locations in space
    rock = create_rock(i_empty - 3, 2, k_rock)
    
    # Drop the rock according to the running count of jets
    dropping_flag = True
    while dropping_flag:
        # Try to apply the jets and drop the rock
        rock, dropping_flag = update(rock, k_jet)
        k_jet = (k_jet + 1) % n
    
    # Finalize the position of the rock and update the index of the lowest empty row
    for i,j in rock:
        cave[i,j] = True
        i_empty = min(i_empty, i-1)

# Answer
len(cave) - i_empty - 2

3059

## 2 test

We're dropping 1 trillion rocks: obviously running the full simulation won't work out! So there has to be a trick:
- The rock pattern probably cycles after a certain point
- The main input gives 10093 jets (prime) and there are 5 rocks, so at some point it must be true that we get back to rock 0 and jet 0
- Let's see how long that takes, and if the rocks cycle after that

In [135]:
# Parse the input
jets = clean(t)
n = len(jets)

# Empty cave
cave = np.zeros((8100, 7), dtype=bool)

# Rock floor
cave[-1,:] = True

# Number of rocks to drop
num_rocks = 5000

# Keep a running counter of which jet we're using next
k_jet = 0

# And an index for the lowest empty row
i_empty = 8098

# Keep track to look for cycles
record = []

# Iterate through rocks
for k in range(num_rocks):    
    # For peace of mind:
    assert i_empty > 10
    
    # The rock we'll drop
    k_rock = k % 5
    
    # Before dropping each rock, record the current rock, jet, number of rocks dropped, and height
    record += [(k_rock, k_jet, k, i_empty)]
    
    # Create the rock as its locations in space
    rock = create_rock(i_empty - 3, 2, k_rock)
    
    # Drop the rock according to the running count of jets
    dropping_flag = True
    while dropping_flag:
        # Try to apply the jets and drop the rock
        rock, dropping_flag = update(rock, k_jet)
        k_jet = (k_jet + 1) % n
    
    # Finalize the position of the rock and update the index of the lowest empty row
    for i,j in rock:
        cave[i,j] = True
        i_empty = min(i_empty, i-1)

It looks like we enter into a cycle of 35 rocks with height 53 pretty quickly! I could verify it by checking the cave, but surely this is not some insane fluke.

In [136]:
d = {}
for rock, jet, k, i in record:
    if (rock,jet) in d:
        print(*d[(rock,jet)])
        print(rock, jet, k, i)
        break
    d[(rock,jet)] = (rock,jet,k,i)

0 2 15 8073
0 2 50 8020


In [137]:
# Printing the number of rocks and height along this cycle
for rock, jet, k, i in record:
    if rock == 0 and jet == 2:
        print(k,i)

15 8073
50 8020
85 7967
120 7914
155 7861
190 7808
225 7755
260 7702
295 7649
330 7596
365 7543
400 7490
435 7437
470 7384
505 7331
540 7278
575 7225
610 7172
645 7119
680 7066
715 7013
750 6960
785 6907
820 6854
855 6801
890 6748
925 6695
960 6642
995 6589
1030 6536
1065 6483
1100 6430
1135 6377
1170 6324
1205 6271
1240 6218
1275 6165
1310 6112
1345 6059
1380 6006
1415 5953
1450 5900
1485 5847
1520 5794
1555 5741
1590 5688
1625 5635
1660 5582
1695 5529
1730 5476
1765 5423
1800 5370
1835 5317
1870 5264
1905 5211
1940 5158
1975 5105
2010 5052
2045 4999
2080 4946
2115 4893
2150 4840
2185 4787
2220 4734
2255 4681
2290 4628
2325 4575
2360 4522
2395 4469
2430 4416
2465 4363
2500 4310
2535 4257
2570 4204
2605 4151
2640 4098
2675 4045
2710 3992
2745 3939
2780 3886
2815 3833
2850 3780
2885 3727
2920 3674
2955 3621
2990 3568
3025 3515
3060 3462
3095 3409
3130 3356
3165 3303
3200 3250
3235 3197
3270 3144
3305 3091
3340 3038
3375 2985
3410 2932
3445 2879
3480 2826
3515 2773
3550 2720
3585 2667
36

In [154]:
# This matches the expect answer because the average height gained per rock is about equal to 53/35
print(1514285714288 / 1000000000000)
print(53/35)

1.514285714288
1.5142857142857142


(You even use continued fractions to guess at the cycle length! But that's not precise enough for what we want.)

Now to turn that into an answer, account for the bulk of the height with these cycles and the remaining height through simulation

In [160]:
target_rocks = 1000000000000
target_rocks // 35

28571428571

In [161]:
# So let's assume 999999999950 rocks are accounted for via this method
# (Being a bit conservative to avoid any edge effects)
28571428570 * 35

999999999950

In [162]:
# That contributes a height of 1514285714210
28571428570 * 53

1514285714210

Now find the height of the remaining 50 rocks

In [158]:
# Parse the input
jets = clean(t)
n = len(jets)

# Empty cave
cave = np.zeros((8100, 7), dtype=bool)

# Rock floor
cave[-1,:] = True

# Number of rocks to drop
num_rocks = 50

# Keep a running counter of which jet we're using next
k_jet = 0

# And an index for the lowest empty row
i_empty = 8098

# Iterate through rocks
for k in range(num_rocks):    
    # For peace of mind:
    assert i_empty > 10
    
    # The rock we'll drop
    k_rock = k % 5
    
    # Create the rock as its locations in space
    rock = create_rock(i_empty - 3, 2, k_rock)
    
    # Drop the rock according to the running count of jets
    dropping_flag = True
    while dropping_flag:
        # Try to apply the jets and drop the rock
        rock, dropping_flag = update(rock, k_jet)
        k_jet = (k_jet + 1) % n
    
    # Finalize the position of the rock and update the index of the lowest empty row
    for i,j in rock:
        cave[i,j] = True
        i_empty = min(i_empty, i-1)

In [159]:
len(cave) - i_empty - 2

78

In [163]:
# All together
1514285714210 + 78

1514285714288

It worked!

## 2 run

Simluate more to be sure of the cycle

In [170]:
# Parse the input
jets = clean(s)
n = len(jets)

# Empty cave
cave = np.zeros((20000, 7), dtype=bool)

# Rock floor
cave[-1,:] = True

# Number of rocks to drop
num_rocks = 10000

# Keep a running counter of which jet we're using next
k_jet = 0

# And an index for the lowest empty row
i_empty = 20000-2

# Keep track to look for cycles
record = []

# Iterate through rocks
for k in range(num_rocks):    
    # For peace of mind:
    assert i_empty > 10
    
    # The rock we'll drop
    k_rock = k % 5
    
    # Before dropping each rock, record the current rock, jet, number of rocks dropped, and height
    record += [(k_rock, k_jet, k, i_empty)]
    
    # Create the rock as its locations in space
    rock = create_rock(i_empty - 3, 2, k_rock)
    
    # Drop the rock according to the running count of jets
    dropping_flag = True
    while dropping_flag:
        # Try to apply the jets and drop the rock
        rock, dropping_flag = update(rock, k_jet)
        k_jet = (k_jet + 1) % n
    
    # Finalize the position of the rock and update the index of the lowest empty row
    for i,j in rock:
        cave[i,j] = True
        i_empty = min(i_empty, i-1)

In [171]:
d = {}
for rock, jet, k, i in record:
    if (rock,jet) in d:
        print(*d[(rock,jet)])
        print(rock, jet, k, i)
        break
    d[(rock,jet)] = (rock,jet,k,i)

2 934 162 19754
2 934 1882 17145


In [172]:
# Printing the number of rocks and height along this cycle
for rock, jet, k, i in record:
    if rock == 2 and jet == 934:
        print(k,i)

162 19754
1882 17145
3597 14571
5312 11997
7027 9423
8742 6849


In [175]:
print(1882 - 162, 19754 - 17145)
print(3597  - 1882, 17145 - 14571)
print(5312  - 3597 , 14571 - 11997)
print(7027  - 5312 , 11997 - 9423)
print(8742  - 7027, 9423 - 6849)

1720 2609
1715 2574
1715 2574
1715 2574
1715 2574


So after nearly 2000 rocks we enter a cycle of 1715 rocks with height 2574

In [178]:
# Ballpark of expected answer
int(1000000000000 / 1715 * 2574)

1500874635568

In [176]:
target_rocks = 1000000000000
target_rocks // 1715

583090379

In [180]:
# So let's assume 999999996555 rocks are accounted for via this method
# (Being a bit conservative to avoid any edge effects)
583090377 * 1715

999999996555

In [181]:
# How many are left
target_rocks - 999999996555

3445

In [182]:
# Tha accounted for rocks contribute a height of 1500874630398
583090377 * 2574

1500874630398

Now find the height of the remaining 3445 rocks

In [187]:
# Parse the input
jets = clean(s)
n = len(jets)

# Empty cave
cave = np.zeros((20000, 7), dtype=bool)

# Rock floor
cave[-1,:] = True

# Number of rocks to drop
num_rocks = 3445

# Keep a running counter of which jet we're using next
k_jet = 0

# And an index for the lowest empty row
i_empty = 20000-2

# Iterate through rocks
for k in range(num_rocks):    
    # For peace of mind:
    assert i_empty > 10
    
    # The rock we'll drop
    k_rock = k % 5
    
    # Create the rock as its locations in space
    rock = create_rock(i_empty - 3, 2, k_rock)
    
    # Drop the rock according to the running count of jets
    dropping_flag = True
    while dropping_flag:
        # Try to apply the jets and drop the rock
        rock, dropping_flag = update(rock, k_jet)
        k_jet = (k_jet + 1) % n
    
    # Finalize the position of the rock and update the index of the lowest empty row
    for i,j in rock:
        cave[i,j] = True
        i_empty = min(i_empty, i-1)

In [188]:
len(cave) - i_empty - 2

5189

In [189]:
# Final answer (really close to the ballpark, which is good)
1500874630398 + 5189

1500874635587

It worked! Bless. I would not have been excited to figure out where I went wrong, or to be more careful about how I detect cycles. I did implicitly assume if it looked like a cycle then it was a cycle. But unless the cycle breaks down after 4 goes around (which is what I checked up to; and achieving this would take some *insanely* clever problem design), there's no issue.

It might look like I just guessed (cycle part) + (manual part) was fine and I got lucky, but there is a rigorous argument there: if you imagine the whole stack of "moves" (whatever the reasonable definition of move is here), it's really just a long sequence of the main cycling block bookended by a lead-in and a partial cycle at the end. If we remove the middle stuff, the stuff that's left is an initial sequence of dropping rocks. Hence we can remove the cycle part (and account for its height separately), and what we're left with is a sequence of rock drops that can be directly simulated.

Or you can argue that our known cycle implies that same cycle if you start with a later rock (i.e. if rock k is the start of the cycle, rock k+1 is the start of a separate cycle with the same height). So you can instead think that the last rock dropped (rock 1,000,000,000,000) is the last rock of the cycle we care about, so just account for all but the first few rocks as coming from that cycle and simluate the first rocks dropped up until the start of this cycle).

# Utilities

In [3]:
# Remove initial/final \n characters
def clean(s):
    return s[1:-1]

# Split at \n characters
# If there are \n\n characters, split into blocks too
def split(s, block_char = '\n\n', line_char = '\n'):
    out = [block.split(line_char) for block in clean(s).split(block_char)]
    if len(out) == 1:
        return out[0]
    else:
        return out

# Apply a function(s) to a list or "block" data (2-level list)
def apply_func(data, func, nested=False):
    if not isinstance(func, list):
        func = [func]
        
    def _func(x):
        for f in func:
            x = f(x)
        return x
        
    if nested:
        return [[_func(x) for x in block] for block in data]
    else:
        return [_func(x) for x in data]

# Split, parsing everything as ints
def split_int(s):
    return apply_func(split(s), int)

# Split, parsing everything as float
def split_float(s):
    return apply_func(split(s), float)

# Inputs

In [2]:
t = """
>>...>>
"""

In [1]:
s = """
>>...>>
"""